Require Export CT.Instance.Category.ArrowCategory.
Require Export CT.Instance.Category.Cat.
Require Export CT.Instance.Category.FunctorCategory.
Require Export CT.Instance.Category.GroupCategory.
Require Export CT.Instance.Category.MonoidCategory.
Require Export CT.Instance.Category.Opposite.
Require Export CT.Instance.Category.ProductCategory.
Require Export CT.Instance.Coq.Category.
Require Export CT.Instance.Coq.Functor.
Require Export CT.Instance.Functor.Bifunctor.
Require Export CT.Instance.Functor.ComposeFunctor.
Require Export CT.Instance.Functor.ConstantFunctor.
Require Export CT.Instance.Functor.ContravariantFunctor.
Require Export CT.Instance.Functor.Endofunctor.
Require Export CT.Instance.Functor.FaithfulFunctor.
Require Export CT.Instance.Functor.FAlgebra.
Require Export CT.Instance.Functor.FullFunctor.
Require Export CT.Instance.Functor.FullyFaithfulFunctor.
Require Export CT.Instance.Functor.IdentityFunctor.
Require Export CT.Instance.Functor.OppositeFunctor.
Require Export CT.Instance.Functor.ProductFunctor.
Require Export CT.Instance.Functor.Profunctor.
Require Export CT.Instance.Isomorphism.
Require Export CT.Instance.NaturalTransformation.Composition.
Require Export CT.Instance.NaturalTransformation.HCNaturalTransformation.
Require Export CT.Instance.NaturalTransformation.IdentityNaturalTransformation.
Require Export CT.Instance.NaturalTransformation.NaturalIsomorphism.
Require Export CT.Instance.NaturalTransformation.VCNaturalTransformation.
(* This file is auto-generated. *)
